version: "3.9"
services:
  backend:
    stdin_open: true
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    network_mode: "host"
    depends_on:
      - backend

volumes:
  postgres-data:
  pgadmin-data:
