version: "3.9"
services:
  backend:
    hostname: backend
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - chatapp
  frontend:
    hostname: frontend
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - chatapp
networks:
  chatapp:
    external:
      name: chatapp
